### ISSUE TITLE
Only first batch of servers.

### ISSUE THREAD

**Issue by jarkomes** [gepo/hetzner-cost-estimator#1]
Hello,

Ive been testing your little program and it looks promising, I only have 1 issue with it.
I only get the first 50(?) servers, but would need a report of the complete server list (140+).

Is this something you would be able to look into?

Thanks,
jarkomes

**Comment by gepo** [comment]
I have no account with more than 50 servers for testing, you can create PR for this or send me your account credentials (for you own risk).

**Comment by jarkomes** [comment]
I cant give you our account, but I looked a bit further in the code. I think you use:
https://robot.your-server.de/server to get the servers, but in fact when you have 50+ servers you get 1 page per 50 servers like this:
https://robot.your-server.de/server/index/page/1
https://robot.your-server.de/server/index/page/2
https://robot.your-server.de/server/index/page/3
...

I would suggest that there is a flag created which can be set with how many pages it has to check?
I can look in the code tomorrow, but cant promise anything!

Kr,
jarkomes
